### PR TITLE
Feature/cloud 757 create dms module

### PR DESCRIPTION
**Pull request by LeeHughsVariant**
# Description

Added DMS Instance module

[CLOUD-757](https://usxtech.atlassian.net/browse/CLOUD-757)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

```text
Ran locally as root module. One thing to note when testing, check for the existence of these 3 IAM roles:

1. dms-access-for-endpoint
2. dms-cloudwatch-logs-role
3. dms-vpc-role

These roles are automatically created when a DMS instance is created for the first time from the AWS console. These roles are not automatically created when creating a DMS instance for the first time via CLI/API call. In order to prevent having a manual step of creating these roles in a fresh account, this module will create these roles for you, but if they already exist it will fail. If these roles exist, delete them.

Example .tfvars.json file has been provided in the README.md

```

- [ ] Sanity Testing

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added documentation to test

### CODE REVIEW

**Comment by rchengvariant** [comment]
I was able to create the DMS instance from my local. As per the conversation, this module will fail if another user attempts to create an instance locally in the same account since the IAM name will already exist in the account while the state files are on two local machines. I think (big emphasis on think) this happens because we are hardcoding the iam name?
```
resource "aws_iam_role" "dms-access-for-endpoint" {
  assume_role_policy = data.aws_iam_policy_document.dms_assume_role.json
  name               = "dms-access-for-endpoint"
}
```

**Comment by rchengvariant** [comment]
Screen Shot 2021-09-10 at 1 43 54 PM
Screen Shot 2021-09-10 at 1 44 19 PM

**Comment by LeeHughsVariant** [comment]
> I was able to create the DMS instance from my local. As per the conversation, this module will fail if another user attempts to create an instance locally in the same account since the IAM name will already exist in the account while the state files are on two local machines. I think (big emphasis on think) this happens because we are hardcoding the iam name? @vibindaniel
> 
> ```
> resource "aws_iam_role" "dms-access-for-endpoint" {
>   assume_role_policy = data.aws_iam_policy_document.dms_assume_role.json
>   name               = "dms-access-for-endpoint"
> }
> ```

Note. The name **has** to be hardcoded, because AWS expects these roles to exist with these exact names in order to create DMS instances. As long as this module is only used with the same tf-state per account (probably lazy-tf-state), then it will be fine. Alternatively, I can remove the IAM role parts, and create them manually in each account before the module can be used for the first time.

**Comment by vibindaniel** [comment]
@LeeHughsVariant Can you prepend the vpc name to the iam-role name?

**Comment by LeeHughsVariant** [comment]
> @LeeHughsVariant Can you prepend the vpc name to the iam-role name?

I can attempt it, and see what happens. But I am pretty sure it will fail. Here is the documentation that goes over the necessity of these roles:
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Security.html#CHAP_Security.APIRole

**Comment by vibindaniel** [comment]
@LeeHughsVariant Can you add those three roles to policies-iam?

**Comment by LeeHughsVariant** [comment]
@vibindaniel @rchengvariant Removed IAM resources.

**Comment by rchengvariant** [comment]
Approved.
Screen Shot 2021-09-13 at 4 39 32 PM
Screen Shot 2021-09-13 at 4 40 21 PM

**Review by rchengvariant — APPROVED** [review]

**Pull request merged**
